#!/bin/bash
#LOG=log_latencytests.txt
#KSRC=/home/pi/kaiwantech/linux-5.0
#LAT=~/booksrc/ch7/latency_test/
KSRC=/home/kai/big/kernel/linux-5.0
LAT=~/booksrc_LKDC/ch7/latency_test

echo "================================================================="
date
#${LAT}/latency_test.sh "RPi kernel 5.0 build" &
${LAT}/latency_test.sh "x86_64 kernel 5.0 build" &
(cd ${KSRC}
sync ; date ; time make -j8 all; date ; sync)
sudo pkill cyclictest
date
