#!/bin/bash
#----------------------------------------------------------------------
# This program is part of the source code released for the book
#  "Learn Linux Kernel Development"
#  (c) Author: Kaiwan N Billimoria
#  Publisher:  Packt
#  GitHub repository:
#  https://github.com/PacktPublishing/Learn-Linux-Kernel-Development
#
# For details, refer the book, Ch 11.
#----------------------------------------------------------------------
LAT=~/booksrc/ch11/latency_tests
TIMEOUT_HOURS=1

echo "================================================================="
${LAT}/latency_test.sh "running 'stress'" &
CMD="stress --cpu 6 --io 2 --hdd 4 --hdd-bytes 1MB --vm 2 --vm-bytes 128M --timeout ${TIMEOUT_HOURS}h"
(cd ${KSRC}
sync ; date
echo "${CMD}"
eval "${CMD}"
date ; sync)
sudo pkill cyclictest
date
